In [1]:
import pandas as pd

In [5]:
lou_crime = pd.read_csv('lmpd_crime.csv')

In [6]:
lou_crime.head()

,incident_number,date_reported,date_occurred,badge_id,offense_classification,offense_code_name,nibrs_code,nibrs_group_name,was_offense_completed,lmpd_division,lmpd_beat,location_category,block_address,city,zip_code,ObjectId
0,LMPD25080477,7/11/2025 3:29:00 PM,5/10/2024 4:00:00 AM,2469.0,29 FRAUD IMPERSONATION,THEFT OF IDENTITY OF ANOTHER WITHOUT CONSENT 5...,26C,A,YES,2ND DIVISION,211,RESIDENCE/HOME,600 BLOCK S 44TH ST,LOUISVILLE,40211,1
1,LMPD25007349,1/23/2025 5:14:00 PM,12/15/2024 3:40:00 PM,8611.0,19 THEFT FR BLDG,TBUT OR DISP FROM BUILDING 514.030 24160 23D,23D,A,YES,4TH DIVISION,412,RESIDENCE/HOME,900 BLOCK S BROOK ST,LOUISVILLE,40203,2
2,LMPD25077420,7/5/2025 5:42:00 PM,11/1/2024 4:00:00 AM,7090.0,13 BURGLARY,BURGLARY - 2ND DEGREE 511.030 22061 220,220,A,YES,7TH DIVISION,736,RESIDENCE/HOME,1000 BLOCK MEADOW HILL RD,LOUISVILLE,40219,3
3,LMPD25067785,6/13/2025 11:18:00 PM,9/15/2024 4:00:00 PM,8544.0,23 LARCENY,TBUT OR DISP ALL OTHERS 514.030 24095 23H,23H,A,YES,5TH DIVISION,521,INDUSTRIAL SITE,2600 BLOCK BUDDEKE DR,LOUISVILLE,40206,4
4,LMPD25007340,1/23/2025 4:48:00 PM,3/1/2024 5:01:00 AM,8358.0,29 FRAUD IMPERSONATION,THEFT OF IDENTITY OF ANOTHER WITHOUT CONSENT 5...,26C,A,YES,2ND DIVISION,223,RESIDENCE/HOME,3300 BLOCK KIRBY AVE,LOUISVILLE,40211,5

In [8]:
lou_crime.columns

Index(['incident_number', 'date_reported', 'date_occurred', 'badge_id',
       'offense_classification', 'offense_code_name', 'nibrs_code',
       'nibrs_group_name', 'was_offense_completed', 'lmpd_division',
       'lmpd_beat', 'location_category', 'block_address', 'city', 'zip_code',
       'ObjectId'],
      dtype='object')

In [9]:
lou_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70746 entries, 0 to 70745
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   incident_number         70746 non-null  object
 1   date_reported           70739 non-null  object
 2   date_occurred           70746 non-null  object
 3   badge_id                70742 non-null  float64
 4   offense_classification  70615 non-null  object
 5   offense_code_name       70744 non-null  object
 6   nibrs_code              70746 non-null  object
 7   nibrs_group_name        70746 non-null  object
 8   was_offense_completed   70746 non-null  object
 9   lmpd_division           70501 non-null  object
 10  lmpd_beat               70465 non-null  object
 11  location_category       70705 non-null  object
 12  block_address           69634 non-null  object
 13  city                    70746 non-null  object
 14  zip_code                70740 non-null  object
 15  ObjectId                70746 non-null  int64
dtypes: float64(1), int64(1), object(14)
memory usage: 8.6+ MB

In [10]:
lou_crime.shape

(70746, 16)

In [14]:
lou_crime.describe()

            badge_id      ObjectId
count   70742.000000  70746.000000
mean     6528.416881  35373.500000
std      4024.086633  20422.755409
min      2013.000000      1.000000
25%      5391.000000  17687.250000
50%      5588.000000  35373.500000
75%      8185.000000  53059.750000
max    999950.000000  70746.000000

In [15]:
lou_crime.value_counts()

incident_number  date_reported          date_occurred          badge_id  offense_classification    offense_code_name                                                     nibrs_code  nibrs_group_name  was_offense_completed  lmpd_division  lmpd_beat  location_category           block_address                city        zip_code  ObjectId
240219129        7/2/2024 1:04:00 AM    7/2/2024 1:04:00 AM    5583.0    13 BURGLARY               BURGLARY - 1ST DEGREE 511.020 22060 220                               220         A                 YES                    3RD DIVISION   315        RESIDENCE/HOME              8700 BLOCK COTTINGHAM WAY    LOUISVILLE  40258     36770       1
LMPD24108636     9/16/2024 11:42:00 PM  9/16/2024 11:42:00 PM  7590.0    24 VANDALISM              CRIMINAL MISCHIEF - 1ST DEGREE 512.020 01401 290                      290         A                 YES                    7TH DIVISION   711        PARKING/ DROP LOT/ GARAGE   5300 BLOCK BARDSTOWN RD      LOUISVILLE  40291     20586       1
LMPD24108610     9/16/2024 10:06:00 PM  9/16/2024 10:06:00 PM  5275.0    46 FAMILY OFFENSES        VIOLATION OF KENTUCKY EPO/DVO 403.763 02763 90F                       90F         B                 NO                     1ST DIVISION   111        RESIDENCE/HOME              2500 BLOCK MONTGOMERY ST     LOUISVILLE  40212     20628       1
                                                                         46 WPNS LAW VIOLATION     POSSESSION OF FIREARM BY CONVICTED FELON 527.040 52196 520            520         A                 YES                    1ST DIVISION   111        RESIDENCE/HOME              2500 BLOCK MONTGOMERY ST     LOUISVILLE  40212     20642       1
                                                                         9 AGGRAVATED ASSAULT      WANTON ENDANGERMENT-1ST DEGREE 508.060 13201 13A                      13A         A                 YES                    1ST DIVISION   111        RESIDENCE/HOME              2500 BLOCK MONTGOMERY ST     LOUISVILLE  40212     20633       1
                                                                                                                                                                                                                                                                                                                                                  ..
LMPD24058038     5/20/2024 2:20:00 PM   5/20/2024 10:20:00 AM  8611.0    28 FRAUD CREDIT CARD/ATM  FRAUDULENT USE OF A CREDIT CARD 434.650(1)(B) 71200 26B               26B         A                 YES                    1ST DIVISION   111        GROCERY/ SUPERMARKET        2200 BLOCK W MARKET ST       LOUISVILLE  40212     45426       1
LMPD24058040     5/20/2024 2:24:00 PM   5/20/2024 2:37:00 PM   5129.0    22 THEFT MV PARTS         THEFT OF MOTOR VEHICLE REGISTRATION PLATE/DECAL 186.990(6) 28200 23G  23G         A                 YES                    1ST DIVISION   111        RESIDENCE/HOME              2700 BLOCK W MAIN ST         LOUISVILLE  40212     45425       1
LMPD24058041     5/8/2024 2:27:00 PM    2/1/2024 5:00:00 AM    7283.0    4 FORCIBLE RAPE           RAPE - 2ND DEGREE (INTELLECTUAL DISABILITY) 510.050 11168 11A         11A         A                 YES                    8TH DIVISION   823        RESIDENCE/HOME              14600 BLOCK LANDIS VILLA DR  LOUISVILLE  40245     47706       1
LMPD24058043     5/19/2024 2:00:00 PM   5/19/2024 2:00:00 PM   5115.0    24 VANDALISM              CRIMINAL MISCHIEF-3RD DEGREE 512.040 01403 290                        290         A                 YES                    7TH DIVISION   735        GROCERY/ SUPERMARKET        4900 BLOCK OUTER LOOP        LOUISVILLE  40219     45382       1
LMPD25902583     11/12/2024 5:30:00 PM  11/12/2024 5:30:00 PM  8185.0    23 LARCENY                TBUT OR DISP ALL OTHERS $1,000 < $10,000 514.030 24097 23H            23H         A                 YES                    6TH DIVISION   613        COMMERCIAL/OFFICE BUILDING  4600 BLOCK ILLINOIS AVE      LOUISVILLE  40213     9340        1
Name: count, Length: 69184, dtype: int64

In [20]:
lou_crime.isnull().sum() * 100 / len(lou_crime)

incident_number           0.000000
date_reported             0.009895
date_occurred             0.000000
badge_id                  0.005654
offense_classification    0.185169
offense_code_name         0.002827
nibrs_code                0.000000
nibrs_group_name          0.000000
was_offense_completed     0.000000
lmpd_division             0.346309
lmpd_beat                 0.397196
location_category         0.057954
block_address             1.571820
city                      0.000000
zip_code                  0.008481
ObjectId                  0.000000
dtype: float64

In [21]:
lou_crime[lou_crime['block_address'].isna()]

,incident_number,date_reported,date_occurred,badge_id,offense_classification,offense_code_name,nibrs_code,nibrs_group_name,was_offense_completed,lmpd_division,lmpd_beat,location_category,block_address,city,zip_code,ObjectId
141,LMPD25002561,1/9/2025 5:47:00 PM,10/2/2024 4:00:00 AM,8585.0,22 THEFT MV PARTS,THEFT OF MOTOR VEHICLE REGISTRATION PLATE/DECA...,23G,A,YES,2ND DIVISION,223,PARKING/ DROP LOT/ GARAGE,NaN,LOUISVILLE,40210,142
250,LMPD25094869,8/13/2025 9:32:00 PM,7/5/2024 6:00:00 AM,5388.0,24 VANDALISM,CRIMINAL MISCHIEF-2ND DEGREE 512.030 01402 290,290,A,YES,2ND DIVISION,223,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40211,251
251,LMPD25094869,8/13/2025 9:32:00 PM,7/5/2024 6:00:00 AM,5388.0,9 AGGRAVATED ASSAULT,WANTON ENDANGERMENT 1ST - DISCHARGE OF FIREARM...,13A,A,YES,2ND DIVISION,223,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40211,252
258,LMPD25089674,8/1/2025 10:30:00 PM,11/28/2024 12:00:00 AM,8584.0,22 THEFT MV PARTS,THEFT OF MOTOR VEHICLE REGISTRATION PLATE/DECA...,23G,A,YES,2ND DIVISION,234,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40210,259
311,LMPD25009782,1/29/2025 6:55:00 PM,12/13/2024 11:00:00 PM,5623.0,9 AGGRAVATED ASSAULT,WANTON ENDANGERMENT 1ST - DISCHARGE OF FIREARM...,13A,A,YES,1ST DIVISION,111,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40212,312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70646,8023012144,2/21/2023 10:50:00 AM,11/3/2024 7:23:00 PM,8402.0,33 STOLEN PROPERTY,RECEIVING STOLEN PROPERTY (FIREARM) 514.110 28...,280,A,YES,1ST DIVISION,112,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40203,70647
70655,8021034150,6/14/2021 12:00:00 AM,1/10/2024 11:20:00 PM,7573.0,33 STOLEN PROPERTY,RECEIVING STOLEN PROPERTY (FIREARM) 514.110 28...,280,A,YES,1ST DIVISION,111,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40212,70656
70658,8021029830,5/26/2021 9:10:00 AM,4/7/2024 7:09:00 AM,5212.0,33 STOLEN PROPERTY,RECEIVING STOLEN PROPERTY (FIREARM) 514.110 28...,280,A,YES,2ND DIVISION,223,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40210,70659
70661,8023004987,1/22/2023 5:01:00 AM,12/27/2024 6:30:00 PM,8358.0,33 STOLEN PROPERTY,RECEIVING STOLEN PROPERTY (FIREARM) 514.110 28...,280,A,YES,2ND DIVISION,212,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40211,70662
70734,LMPD24000043,1/1/2024 7:20:00 AM,1/1/2024 7:20:00 AM,5516.0,23 THEFT OTHER,TBUT OR DISP FIREARM 514.030 23100 23H,23H,A,YES,3RD DIVISION,322,HIGHWAY/ ROAD/ ALLEY/ STREET/ SIDEWALK,NaN,LOUISVILLE,40214,70735

In [22]:
lou_crime.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
70741    False
70742    False
70743    False
70744    False
70745    False
Length: 70746, dtype: bool